# This Docker Compose file adds/overrides some elements of the docker-compose.yml file
# This file is run using docker-compose up, this is to run a development version

version: '3.3'

services:

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    environment:
      - CI=true
    volumes:
        - ./frontend:/src
    ports:
      - "3000:3000"
    depends_on:
      - db
      - wordpress
    command: npm start