# This Docker Compose file adds/overrides some elements of the docker-compose.yml file
# This file is run using docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d 
# This is to run a production version

version: '3.2'

services:
  web:
    command: bash -c "
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py collectstatic --noinput && 
      gunicorn main.wsgi -b 0.0.0.0:8000 --reload"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/src
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  